PREFIX = /usr
BINDIR = $(PREFIX)/bin
DESTDIR = 
LIBDIR = $(PREFIX)/lib
SYSCONFDIR = /etc

all:
	

clean:
	

install:
	mkdir -p $(DESTDIR)$(LIBDIR)/molecule/molecule
	cp *.py specs $(DESTDIR)$(LIBDIR)/molecule/molecule -Ra
