PREFIX = /usr
BINDIR = $(PREFIX)/bin
DESTDIR = 
LIBDIR = $(PREFIX)/lib
SYSCONFDIR = /etc

all:
	

clean:
	

install:
	install -d $(DESTDIR)$(LIBDIR)/molecule/molecule/specs/plugins
	install -m 644 *.py $(DESTDIR)$(LIBDIR)/molecule/molecule/specs/plugins/
